# Generated by Django 5.2.6 on 2025-09-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('delivery_man', 'Delivery Man'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
