# Generated by Django 5.2.6 on 2025-09-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('delivery_man', 'Delivery Man'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
